export const GELIST_TRANSACTION_SS = "GELIST_TRANSACTION_SS";
export const GELIST_TRANSACTION_ER = "GELIST_TRANSACTION_ER";
export const LOADING_TRANSACTION = "LOADING_TRANSACTION";
export const ALERT_GET_TRANSACTION_ER= "Lỗi, vui lòng thử lại";
export const OPEN_DETAIL_TRANSACTION = "OPEN_DETAIL_TRANSACTION";
export const OPEN_UPDETE_TRANSACTION = "OPEN_UPDETE_TRANSACTION";
export const CLOSE_MODAL_TRANSACTION = "CLOSE_TRANSACTION";