export const SEND_REQ = "SEND_REQ";
export const LOGIN_SS = "LOGIN_SS";
export const LOGIN_ER = "LOGIN_ER";
export const REGISTER_SS = "REGISTER_SS";
export const REGISTER_ER = "REGISTER_ER";
export const LOGOUT = "LOGOUT";
export const UPDATE_INFO = "UPDATE_INFO";
export const ALERT_UPDATE_SS = "Cập nhật thông tin thành công";
export const ALERT_UPDATE_ER = "Cập nhật thông tin thất bại";
