export const GET_LIST_CATALOG_SS = "GET_LIST_CATALOG_SS";
export const GET_LIST_CATALOG_ER = "GET_LIST_CATALOG_ER";
export const GET_LIST_SELLER_SS = "GET_LIST_SELLER_SS";
export const GET_LIST_SELLER_ER = "GET_LIST_SELLER_ER";
export const SIZE_SELLER = 8;
