export const FETCH_PRODUCT_SS ="FETCH_PRODUCT_SS";
export const FETCH_PRODUCT_ER ="FETCH_PRODUCT_ER";
export const LOADDING_PRODUCT ="LOADDING_PRODUCT";
export const FETCH_LIST = "FETCH_LIST_PRODUCT";
export const MSG_ERR_GET = "MSG_ERR_GET_PRODUCT";
export const UPDATE_ID_CATALOG = "UPDATE_ID_CATALOG";
export const UPDATE_ID_TYPE = "UPDATE_ID_TYPE";